db:
  host: "dcbookmyholiday.cvvndxt972kn.us-east-1.rds.amazonaws.com"
  port: "3306"
  user: "admin"
  password: "administrator"
  database: "BookMyHoliday"

autodiscovery:
  apiId: "17636802"
  flow: "api-main"
  